### ISSUE TITLE
Scholar.Metrics exposing more metrics

### ISSUE THREAD

**Issue by guarilha** [elixir-nx/scholar#112]
hey folks, as usual great work on the lib. 

I am using it and was missing ROC-AUC, which would be awesome if the lib already provided it. 
Here is a good reference on useful metrics, formulae and meanings: https://en.wikipedia.org/wiki/Receiver_operating_characteristic

Maybe it would be nice to have all these metrics on scholar? 

thanks

**Comment by msluszniak** [comment]
I can implement ROC-AUC ;)

**Comment by guarilha** [comment]
thanks, @msluszniak!
