### ISSUE TITLE
silhouette samples performance

### ISSUE THREAD

**Issue by santiago-imelio** [elixir-nx/scholar#113]
Hello!

I'm currently playing around with the California Housing dataset (20640 rows) and following examples from a basic ML project of a Python book that uses Scikit-Learn. 

In the custom transformers section it creates a transformer that calculates geo clusters in the data using KMeans and then calculates Gaussian RBF similarity for each point to each cluster using a `rbf_kernel` function. 

In my case, I decided to use `Scholar.Metrics.silhouette_samples` instead of rbf kernel (couldn't find it in Scholar), which worked fine given that the graphic I got looks practically the same as the one in the book (attached images at the end).

However, I noticed that running `silhouette_samples/3` on this dataset takes more than a minute to finish and CPU usage sky rockets. Is this function not optimized or is it just very expensive in resources? 

I'm running a local livebook in a MacBook Air M1 with this setup:

```
Mix.install([
  {:nx, "~> 0.2"},
  {:exla, "~> 0.5"},
  {:scholar, "~> 0.1"},
  {:req, "~> 0.3"},
  {:explorer, "~> 0.5.0"},
  {:vega_lite, "~> 0.1.6"},
  {:kino_vega_lite, "~> 0.1.7"},
  {:kino_explorer, "~> 0.1.7"}
])

Nx.global_default_backend(EXLA.Backend)
```
<img width="633" alt="Screen Shot 2023-06-10 at 18 00 58" src="https://github.com/elixir-nx/scholar/assets/82551777/8ba6d86d-5793-4a41-a2cb-3ee0e1dfda3a">
<img width="665" alt="Screen Shot 2023-06-10 at 18 00 44" src="https://github.com/elixir-nx/scholar/assets/82551777/24609df3-0d12-4388-8750-4d73635831b4">

**Comment by msluszniak** [comment]
Hi,

I guess the problem might be [here](https://github.com/elixir-nx/scholar/blob/main/lib/scholar/metrics/clustering.ex#L110) because we calculating here pairwise distances between matrices that are shape {20640, 20640, 8} which is time consuming. I will look how we can improve this part.

**Comment by polvalente** [comment]
Please also configure Nx.Defn.default_options(compiler: EXLA)

I believe part of the slowdown is due to the defn operations not being compiled with EXLA too.

**Comment by santiago-imelio** [comment]
> Please also configure Nx.Defn.default_options(compiler: EXLA)
> 
> I believe part of the slowdown is due to the defn operations not being compiled with EXLA too.

That was it, now it only took 0.6s :) Thank you!
