### ISSUE TITLE
Add classification and regression metrics

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/scholar#122]
I want to add all the existing metrics which are present in Sci-kit Learn. 

**Classification Metrics**
* [x] Accuracy
* [x] AUC
* [x] Average Precision (AP)
* [x] Balanced Accuracy
* [x] Brier Score Loss
* [x] Cohen Kappa Score
* [x] Confusion Matrix
* [x] Discounted Cumulative Gain (DCG)
* [x] Detection Error Tradeoff Curve (DET curve)
* [x] F1 Score 
* [x] F-beta Score
* [x] Hamming Loss
* [x] Log Loss
* [x] Matthews correlation coefficient (MCC)
* [x] Normalized Discounted Cumulative Gain (Normalized DCG)
* [x] Precision Recall Curve
* [x] Precision Recall Fscore Support
* [x] Precision
* [x] Recall
* [x] ROC-AUC 
* [x] ROC Curve
* [x] Top-k Accuracy Score
* [x] Zero-one Classification Loss

**Regression Metrics**
* [x] Explained Variance Score
* [x] Maximum Residual Error
* [x] Mean Absolute Error (MAE)
* [x] Mean Squared Error (MSE)
* [x] Mean Squared Log Error
* [x] Mean Absolute Percentage Error (MAPE)
* [x] $R^2$ Score
* [x] Mean Poisson deviance
* [x] Mean Gamma deviance
* [x] Mean Tweedie deviance
* [x] $D^2$ - Fraction of Tweedie Deviance Explained
* [x] Mean Pinball Loss
* [x] $D^2$ - Fraction of Pinball Loss Explained
* [x] $D^2$ - Fraction of Absolute Error Explained

We can do the same for distances after (look #149).

**Comment by paulsullivanjr** [comment]
I'd like to contribute to this project. I will start working on a PR for "Discounted Cumulative Gain (DCG)"

**Comment by msluszniak** [comment]
> I'd like to contribute to this project. I will start working on a PR for "Discounted Cumulative Gain (DCG)"

Really cool! Feel free to go :)

**Comment by paulsullivanjr** [comment]
> > I'd like to contribute to this project. I will start working on a PR for "Discounted Cumulative Gain (DCG)"
> 
> Really cool! Feel free to go :)

Going to try to have a PR ready by the end of the week so I can get some feedback.

**Comment by paulsullivanjr** [comment]
I have Normalized DCG in progress.

**Comment by JoaquinIglesiasTurina** [comment]
I have mean pinball loss in progress.

**Comment by srzeszut** [comment]
I am working with @ksew1 and @norm4nn on the remaining metrics.

**Comment by msluszniak** [comment]
We added all metrics, thank all of you who contributed ❤️
