### ISSUE TITLE
Passing key as an option doesn't work

### ISSUE THREAD

**Issue by krstopro** [elixir-nx/scholar#130]
Runnning the example code
https://github.com/elixir-nx/scholar/blob/c4780dbab895e7308821fb57d40700f321c9ccce/lib/scholar/cluster/k_means.ex#L107-L109 gives me

`** (NimbleOptions.ValidationError) unknown options [:key], valid options are: [:num_clusters, :max_iterations, :num_runs, :tol, :weights, :init, :seed]
    (nimble_options 1.0.2) lib/nimble_options.ex:343: NimbleOptions.validate!/2
    (scholar 0.1.0) lib/scholar/cluster/k_means.ex:137: Scholar.Cluster.KMeans.fit/2
    #cell:s5a4sk2ajniowihy7hlnzwxvdc773h7d:3: (file)`

Perhaps the way key option is declared https://github.com/elixir-nx/scholar/blob/c4780dbab895e7308821fb57d40700f321c9ccce/lib/scholar/cluster/k_means.ex#L75-L81 is incorrect?

**Comment by josevalim** [comment]
The key option only exists on main, not on the release v0.1.0. So you need to either use main or follow the docs for v0.1.0 :)
