### ISSUE TITLE
Add Distances

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/scholar#149]
As mentioned in #122 we also want to add all distance metrics. Here is a list that we should probably implement:

* [ ] Sorensen-Dice

It's very little, so adding some proposals in comments to this issue is recommended. For example, we may add kernels like linear kernel or RBF kernel and so on.

**Comment by msluszniak** [comment]
*Haversine distance* accepts only data with shape `{num_samples, 2}` so it wouldn't support `axes` and so on like other distances. Do we want to still add this one? @josevalim

**Comment by josevalim** [comment]
It is fine to skip it!
