### ISSUE TITLE
Change the Structure of Files with Metrics

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/scholar#150]
My idea is to split `lib/scholar/metrics.ex` into `lib/scholar/metrics/classification.ex` and `lib/scholar/metric/regression.ex`. This is because I think that the current structure:

```
/lib/scholar 
| - ...
| - metrics.ex
| - /metrics
    | - distance.ex
    | - clustering.ex
    | - similarity.ex
```                
might be ambiguous because users might not know what is inside metrics.ex when there is a directory called metrics. If we break apart `metrics.ex` into `classification.ex` and `regression.ex`, we will get rid of this ambiguity. The `metrics.ex` is also bulky, so it might be helpful to improve the readability.

```
/lib/scholar 
| - ...
| - /metrics
    | - distance.ex
    | - clustering.ex
    | - similarity.ex
    | - regression.ex
    | - classification.ex
```

**Comment by msluszniak** [comment]
WDYT @josevalim @polvalente?

**Comment by josevalim** [comment]
Do all metrics belong to either classification or regression? Or are there metrics that apply to both?

**Comment by josevalim** [comment]
> There are no metrics that apply to both tasks, but there are some tasks that can be considered as either classification or regression

Can you give some examples? And what would we do about these? Where would they live?

**Comment by msluszniak** [comment]
For example, you can predict the score on IMDB of a single person as a classification (since scores are from discrete set {1, 2, 3, ..., 10}) or you can treat this as a regression task where the score 7.5 is perfectly ok.

**Comment by msluszniak** [comment]
So, there are no somehow combined methods that deal with both regression and classification at the same time.

**Comment by msluszniak** [comment]
After applying the changes, we need to remember to change also livebooks in #117
