### ISSUE TITLE
Handle zero division in metrics

### ISSUE THREAD

**Issue by jonatanklosko** [elixir-nx/scholar#16]
Currently the formulas add `1.0e-16` to avoid zero division, but this unnecessarily impacts valid results. Instead, we should check for zero division and choose a reasonable behaviour.

**Comment by msluszniak** [comment]
My idea is to return 0 or 1 whenever zero division occurs. The default will be set to 0.  It's very similar to the Scikit-Learn approach, except that they also throw a warning. @josevalim

**Comment by josevalim** [comment]
Sounds good! We can also emit the warning if we want by using hooks but we could add them in a future iteration!
