### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kingdomcoding** [elixir-nx/scholar#17]
Hey.

I'm very thankful for this library.

Can a roadmap be added to the Readme so we know where we are and what's in plan for the future?

**Comment by kingdomcoding** [comment]
Thank you @josevalim 

Can I submit a list of scikit-learn features as a PR for you to review?

The review is for completeness and to check off features that have already been developed.

**Comment by josevalim** [comment]
Sounds good. I think we can work on them in the issues first.

Another route is for you to propose a particular feature you want to see and repeat feature after feature (until we structure everything). :)

**Comment by kingdomcoding** [comment]
Alright.

I'll propose a few features asap.

**Comment by josevalim** [comment]
Closing this for now, but, in a nutshell, if sklearn has it, we could (should?) have it. :)
