### ISSUE TITLE
Add general interface to calculate pairwise distances

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/scholar#174]
As mentioned in #172 we may easily create a general interface for pairwise distance calculations.

**Comment by msluszniak** [comment]
@josevalim  I'm wondering which direction we should choose. One way is to have one general function like `pairwise_distance` which accepts an atom with the name of a distance and the rest of the opts. Another way is to have a separate function for each distance.

**Comment by josevalim** [comment]
Can you send a PR with two different distances implemented (or a code comment) so we can discuss which approach may work better with code? :)

**Comment by msluszniak** [comment]
Okay, that sounds good

**Comment by msluszniak** [comment]
Sorry, but I was wrong. There is no general formulation to calculate all pairwise distances for all metrics. From the functions that are available in `Scholar`, only `euclidean`, `squared_euclidean`, and `cosine` can be evaluated faster than simply broadcasting tensors and then using our implemented functions. Because of that, I think that implementing only those three is not worth the effort.

**Comment by josevalim** [comment]
Should we have pairwise_euclidean/pairwise_cosine or not worth it? Does scikit-learn provide anything like this?

**Comment by msluszniak** [comment]
Yes, scikit-learn provides both of them and more. Maybe it's worth having them, but definitely not in the formula I proposed, but as a part of `Scholar.Metrics.Distnaces` :)

**Comment by josevalim** [comment]
Sounds good to me then! :)
