### ISSUE TITLE
Linear interpolation consumes too much memory

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/scholar#182]
The following code

```elixir
Application.ensure_all_started(:exla)
x = Nx.iota({1000000})
y = Nx.iota({1000000})
model = Scholar.Interpolation.Linear.fit(x, y)
EXLA.jit_apply(&Scholar.Interpolation.Linear.predict(&1, &2), [model, x])
```
gives error
```
** (RuntimeError) Out of memory allocating 1031249000016 bytes.
    (exla 0.6.0) lib/exla/executable.ex:56: EXLA.Executable.unwrap!/1
    (exla 0.6.0) lib/exla/executable.ex:19: EXLA.Executable.run/3
    (exla 0.6.0) lib/exla/defn.ex:346: EXLA.Defn.maybe_outfeed/7
    (stdlib 4.2) timer.erl:235: :timer.tc/1
    (exla 0.6.0) lib/exla/defn.ex:283: anonymous fn/7 in EXLA.Defn.__compile__/4
    (nx 0.7.0-dev) lib/nx/defn.ex:433: Nx.Defn.do_jit_apply/3
```
1TB or RAM is for linear interpolation of 1M points, pretty much.  This needs to run smoothly for this number of points because MDS for n samples calculates Linear interpolation for n ^2 samples.

**Comment by msluszniak** [comment]
The problem is this line, introduces quadratic tensor. @polvalente do you have any idea how to implement it in a different way?
https://github.com/elixir-nx/scholar/blob/07405d65b99ed365a0a312604f51b96bd07c716d/lib/scholar/interpolation/linear.ex#L104

**Comment by polvalente** [comment]
@msluszniak a while loop could solve this. Since it would be just to build idx_poly, it should be rather fast. 
I
