### ISSUE TITLE
Cublic Splines works too slow

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/scholar#200]
One of the reasons is that currently, we use `Nx.solve` which is roughly O(n^3), but for tridiagonal matrices, there is a [linear algorithm](https://en.wikipedia.org/wiki/Tridiagonal_matrix_algorithm) that solves the problem.

**Comment by josevalim** [comment]
We should add a `triangular_solve` to Nx perhaps?

**Comment by msluszniak** [comment]
Yes, absolutely. I'll work on that

**Comment by msluszniak** [comment]
For this particular case there is even faster algorithm (Thomas Algorithm) which is O(N) but general triangular solve that is O(N^2) will be also very helpful

**Comment by polvalente** [comment]
We already have triangular_solve
