### ISSUE TITLE
Optimize median

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/scholar#208]
I found [LazySelect](https://dl.acm.org/doi/pdf/10.5555/1882757.1882769) (section 12.2.1). Here is a [numpy implementation](https://github.com/upupming/quick-select/blob/master/src/lazy_selector.py). Improving our median would have benefits for Affinity Propagation. Perhaps to contribute to Nx.

**Comment by krstopro** [comment]
Am I wrong or LazySelect works only with tensors with distinct elements?

**Comment by josevalim** [comment]
@krstopro i don't know actually. Do they mention this exclusively in the paper? It has already been purged from my brain. If that's the case, maybe we can call it `uniq_median` or `distinct_median`.

**Comment by krstopro** [comment]
@josevalim Every reference I see mentions distinct, e.g. [here](https://community.wvu.edu/~krsubramani/courses/sp12/rand/lecnotes/LazySelect.pdf), [here](https://people.cs.umass.edu/~mcgregor/611F20/lec16.pdf), and [here](https://www2.cs.sfu.ca/CourseCentral/405/petra/Current/random2-4up.pdf) (says ordered set, but that should be a sequence without duplicates).

**Comment by josevalim** [comment]
I see. So we either need to pick another algorithm or go with `uniq_median`. I am fine with `uniq_median`.

**Comment by josevalim** [comment]
More algorithms:

* Truncated sort: https://users.cs.duke.edu/~nikos/reprints/knn-TR-CS-2012-03.pdf
* Hierarchical partition: Found at "Efficient Selection Algorithm for Fast k-NN Search on GPUs"

**Comment by krstopro** [comment]
@josevalim wrong issue?

**Comment by josevalim** [comment]
I am thinking we should go ahead with truncated sort. Getting the median of N elements can be done by reshaping it into a matrix of shape `{x, y}`, and then doing the parallel sort on `x` and then doing a sort on the k-first columns of y. We could do `z` rounds, if desired.

**Comment by msluszniak** [comment]
Ok, so what I understand from the paper about truncated sort is that we want to compute a quick select procedure. Is that right?
![image](https://github.com/elixir-nx/scholar/assets/56299341/8bb53b03-65a8-4495-b3d1-ed80a625b75b)

**Comment by josevalim** [comment]
Nx already implements an efficient sorting algorithm. The idea is that to compute the median for the whole tensor (and not on an axis), we can convert the tensor to shape `{x, y}` and then sort them in parallel (using regular Nx.sort on an axis), and then we compute the median, that's all. We wouldn't be implementing any new sorting algorithm in particular.

**Comment by josevalim** [comment]
We can do so benchmarks compared to our regular median implementation.

**Comment by msluszniak** [comment]
Because I thought about this problem to solve using parallel sorting https://cs.stackexchange.com/questions/87695/to-find-median-of-k-sorted-arrays-of-n-elements-each-in-less-than-onk-log

**Comment by msluszniak** [comment]
> I am thinking we should go ahead with truncated sort. Getting the median of N elements can be done by reshaping it into a matrix of shape `{x, y}`, and then doing the parallel sort on `x` and then doing a sort on the k-first columns of y. We could do `z` rounds, if desired.

I think that this approach won't work in general. There are some cases when after a lot of rounds of this procedure the median is still wrong.

**Comment by josevalim** [comment]
Shall we try lazy select then?

**Comment by msluszniak** [comment]
Yes, I think so :)

**Comment by msluszniak** [comment]
Do we have any alternative approaches to check?

**Comment by josevalim** [comment]
The only option left is the "Hierarchical partition" algorithm, section III.E, found at [Efficient Selection Algorithm for Fast k-NN Search on GPUs](https://cs.sjtu.edu.cn/~guo-my/PDF/Conferences/C156.pdf).

**Comment by msluszniak** [comment]
Ok, I'll investigate this option

**Comment by msluszniak** [comment]
I checked the hierarchical partitioning from the paper and I think that it won't help us calculate the median efficiently. The algorithm is an attempt to implement a structure that efficiently fetches k-nearest neighbours when distances are precalculated. They propose an algorithm that runs in O(n) which is worse than min-heap O(k\*log(n)), but it doesn't have a lot of irregular memory accesses like in min-heap. So we potentially can implement median as fetching the n/2 nearest elements to min/max element, but the algorithm doesn't scale well with number of neighbors: "*...  the performance improvement will increase with increasing N and decrease with increasing k. This is because when N is increasing more elements can be excluded. On the contrary, when k is increasing, elements will have more chances to be picked during top-down search.*"
