### ISSUE TITLE
Is this the proper place to put a TF-IDF implementation ?

### ISSUE THREAD

**Issue by mattnenterprise** [elixir-nx/scholar#234]
Searching for a TF-IDF implemention in Elixir typically results in finding older unmaintained libraries. Would this be good place for a TF-IDF implementation ?

**Comment by polvalente** [comment]
I recall @acalejos using something with TF-IDF. I can't recall exactly where

**Comment by josevalim** [comment]
Keep in mind our goal for Scholar is to have pure Nx transformations. I am not sure if TF-IDF can be implemented using only Nx. Perhaps Nx.stream? Otherwise, a NLP focused tooling, like mighty, may be the better place to focus on such tools.

**Comment by acalejos** [comment]
> Keep in mind our goal for Scholar is to have pure Nx transformations. I am not sure if TF-IDF can be implemented using only Nx. Perhaps Nx.stream? Otherwise, a NLP focused tooling, like mighty, may be the better place to focus on such tools.

Good reminder, and I think it's why it currently lives in the repo that it does. I could certainly do work to move much of the functionality into `deftransform`s but I'm not sure about getting to 100%. 

I think it fits naturally in Scholar insofar as if I were looking for TFIDF as an outsider I would probably look to Scholar first, so if  I can get it to be entirely Nx that would be great.

**Comment by josevalim** [comment]
Closing this for now. We are open to an implementation if it can be written in Nx but there is a chance it cannot. :) @acalejos, I believe we discussed this at ElixirConf, and I think the conclusion is that it could not, but I am always glad to be proven wrong. It is definitely worth trying. :)
