### ISSUE TITLE
Implement batch version of brute-force k-NN search

### ISSUE THREAD

**Issue by krstopro** [elixir-nx/scholar#239]
Current implementation of brute-force k-NN search takes $O(N^2 \times D)$ memory for sample size $N$ and dimension $D$. This quickly becomes intractable and can be reduced to $O(B \times N \times D)$ for batch size $B$. This could be important for benchmarking the approximate k-NN methods; in order to calculate the recall one needs to compute the exact nearest neighbors and the only way to do this for large $D$ is via brute-force search.

**Comment by josevalim** [comment]
To be clear, this relates to which module specifically? kNN? RandomForests? KDTree?

**Comment by josevalim** [comment]
It is probably fine to have it there. Maybe we can do separate operations depending on the shape of the input. After all, a single lookup should be equivalent to batch of 1, right?

**Comment by krstopro** [comment]
> It is probably fine to have it there. Maybe we can do separate operations depending on the shape of the input. After all, a single lookup should be equivalent to batch of 1, right?

Or we can set batch as an option with default value of `num_samples`.
