### ISSUE TITLE
CI failing after merge

### ISSUE THREAD

**Issue by krstopro** [elixir-nx/scholar#252]
I think this isn't `Scholar` specific, but maybe `ci.yml` needs to be updated.
<img width="1095" alt="Screenshot 2024-04-07 at 14 17 10" src="https://github.com/elixir-nx/scholar/assets/7234787/5a852922-f85e-449e-ba43-9899e3a57c10">

**Comment by msluszniak** [comment]
I re-run the workflows, and now all is passing :))
