### ISSUE TITLE
Extend Supervised k-NN?

### ISSUE THREAD

**Issue by krstopro** [elixir-nx/scholar#254]
Currently, supervised k-NN model implemented in `Scholar.Neighbors.KNearestNeighbors` uses linear or brute-force search. I think the model should support other methods we have implemented such as k-d tree, random projection forest, etc. We might wanna implement supervised k-NN on top of these.
I would also suggest considering (just considering, I am not sure myself) splitting this module into two: one for classification (e.g. `KNNClassifier`) and one for regression (e.g. `KNNRegressor`).

**Comment by krstopro** [comment]
> Maybe you want some sort of pluggable functionality in order to implement Supervised kNN but then you could make it so you pass the whole module as argument? For example, KNNClassifier with KDTree?

That's what I meant. In order to perform classification or regression, `Scholar.Neighbors.KNearestNeighbors` must first find the nearest neighbors of the query points. Currently, this is done with linear or brute-force search. What I am suggesting is to make this configurable, e.g. by passing an atom as option.

**Comment by josevalim** [comment]
@krstopro what I am trying to suggest is, instead of passing an atom as an option, what if you pass the whole KDTree as an option to KNNClassifier/KNNRegression? You would do this:

    KNNClassifier.fit(..., model: KDTree)

This would keep the current models the same. And you rely on the existing fit/predict contract and build on top of it.

**Comment by krstopro** [comment]
> @krstopro what I am trying to suggest is, instead of passing an atom as an option, what if you pass the whole KDTree as an option to KNNClassifier/KNNRegression? You would do this:
> 
> ```
> KNNClassifier.fit(..., model: KDTree)
> ```
> 
> This would keep the current models the same. And you rely on the existing fit/predict contract and build on top of it.

Yes, that is another possibility I had in mind. Probably the better one. :)
The only problem is: nothing prevents someone to pass a model that has nothing to do with k-NN. Is there a convenient way to enforce this?

**Comment by josevalim** [comment]
@krstopro i would document the supported models well. if someone wants to pass something that is not documented, then they are on their own (sometimes it may be good, it may be a custom knn we not yet implement).

**Comment by krstopro** [comment]
@josevalim Agreed. I was just checking if there is a way to raise an error if someone passes anything that doesn't behave like a k-NN search algorithm.

@msluszniak Any comments from your side?

We might wanna do the same thing with the distances; currently, they are specified as atoms even though we can provide them as functions from `Scholar.Metrics.Distance`.

**Comment by josevalim** [comment]
@krstopro I was going to say that atoms are more convenient for distances but we could support passing a function as well. Maybe we do the same for knn then? We can allow the atoms: `:knn | :kdtree | :random_forest` as short-hand conveniences but allow any module to be given if someone wants to extend it. But they would be atoms to KNNClassifier and KNNRegression. Maybe we should rename KNN to something else that signals it is a brute force approach.

**Comment by krstopro** [comment]
@josevalim Yes, I was thinking of something like that.

**Comment by msluszniak** [comment]
I agree with the approach of using atoms. Specially, because `Sci-kit` learn has almost the same approach (argument `algorithm` with options `brute`, `kdtree` and so on).

**Comment by josevalim** [comment]
Maybe we rename the module to BruteKNN?

**Comment by krstopro** [comment]
> Maybe we rename the module to BruteKNN?

I would suggest `BruteForceKNN`.

**Comment by msluszniak** [comment]
Sounds good :))

**Comment by krstopro** [comment]
@josevalim @msluszniak 
Since we agree, I will take the liberty of moving this to another issue: see #255.
I hope I am not spamming with all the issues and comments these days.
