### ISSUE TITLE
Refactor Scholar.Neighbors

### ISSUE THREAD

**Issue by krstopro** [elixir-nx/scholar#255]
As argued in #254, we need to update `Scholar.Neighbors` in the following way:
- [x] Add `BruteKNN` module that implements brute-force k-NN search. Its `predict` function has to return `{neighbor_indices, neighbor_distances}`. Make `batch_size` an option (as in #253).
- [x] Implement `KNNClassifier`.
- [x] Implement `KNNRegressor`.
- [x] Deprecate `Scholar.Neighbors.KNearestNeighbors`.

`KNNClassifier` and `KNNRegressor` have to take k-NN algorithm and metric options as atoms, but also allow for custom k-NN algorithms and metrics to be passed as modules and functions, respectively.

**Comment by josevalim** [comment]
We don't need to deprecate, we can just rename the module. It should be easy for anyone to just rename it accordingly. :)

**Comment by krstopro** [comment]
> KNNClassifier and KNNRegressor have to take k-NN algorithm and metric options as atoms, but also allow for custom k-NN algorithms and metrics to be passed as modules and functions, respectively.

Is it possible to pass an anonymous function as an option to function defined with `defn`?

**Comment by josevalim** [comment]
Hi @krstopro, I want to release a new version soon. If we plant to remove `Scholar.Neighbors.KNearestNeighbors`, it would be better to do it before, so we update the docs accordingly?

**Comment by josevalim** [comment]
We would also need to mirror those decisions on top of `RadiusNearestNeighbors`.

**Comment by krstopro** [comment]
> Hi @krstopro, I want to release a new version soon. If we plant to remove `Scholar.Neighbors.KNearestNeighbors`, it would be better to do it before, so we update the docs accordingly?

@josevalim Agreed. I will try to implement the stuff from this issue by the end of the week if that's fine.

**Comment by josevalim** [comment]
Perfect. KNN is the most important, Radius can be done later. :)

**Comment by josevalim** [comment]
Thank you @krstopro! I will work on #265 and @msluszniak will update the notebooks. :) Once KNNRegression is ready, we can release a new version!
