### ISSUE TITLE
Use of EXLA in Gradient Boosting guide

### ISSUE THREAD

**Issue by santiago-imelio** [elixir-nx/scholar#273]
Hey, recently it was added to the [Cross-validation with gradient boosting trees guide](https://github.com/elixir-nx/scholar/blob/main/notebooks/cv_gradient_boosting_tree.livemd) the use of EXLA as default backend. However, using EXLA with the XGBoost library seems to break when I run the first training cell. Using `Nx.BinaryBackend` works fine though.

```
** (FunctionClauseError) no function clause matching in Jason.Encoder.Nx.Tensor.encode/2    
    
    The following arguments were given to Jason.Encoder.Nx.Tensor.encode/2:
    
        # 1
        #Nx.Tensor<
          f32
          EXLA.Backend<host:0, 0.2818844854.1719009302.198012>
          NaN
        >
    
        # 2
        {#Function<3.65781566/3 in Jason.Encode.escape_json>,
         #Function<1.65781566/3 in Jason.Encode.map_naive>}
    
    Attempted function clauses (showing 4 out of 4):
    
        def encode(%Nx.Tensor{data: %Nx.BinaryBackend{state: <<32704::integer-native-size(16)>>}}, _opts)
        def encode(%Nx.Tensor{data: %Nx.BinaryBackend{state: <<32256::integer-native-size(16)>>}}, _opts)
        def encode(%Nx.Tensor{data: %Nx.BinaryBackend{state: <<2_143_289_344::integer-native-size(32)>>}}, _opts)
        def encode(%Nx.Tensor{data: %Nx.BinaryBackend{state: <<9_221_120_237_041_090_560::integer-native-size(64)>>}}, _opts)
    
    (exgboost 0.4.0) lib/exgboost/internal.ex:114: Jason.Encoder.Nx.Tensor.encode/2
    (jason 1.4.1) lib/encode.ex:188: Jason.Encode.map_naive/3
    (jason 1.4.1) lib/encode.ex:37: Jason.Encode.encode/2
    (jason 1.4.1) lib/jason.ex:162: Jason.encode!/2
    (exgboost 0.4.0) lib/exgboost/dmatrix.ex:310: EXGBoost.DMatrix.from_tensor/2
    (exgboost 0.4.0) lib/exgboost.ex:215: EXGBoost.train/3
    #cell:gresv4jlhl6cp5ab:2: (file)
```

**Comment by acalejos** [comment]
> You can do `Nx.backend_transfer` or `Nx.backend_copy` accordingly. Can you please send a PR?
> 
> 
> 
> Maybe EXGBoost could raise a clearer message here too /cc @acalejos 

Yes this is a known limitation of EXGBoost currently. 

https://github.com/acalejos/exgboost/issues/41

Errors should be more verbose at least in the meantime until EXLA is better supported, but this overall is an issue with EXGBoost and not Scholar

**Comment by acalejos** [comment]
In particular this is the cause of the issue

https://github.com/acalejos/exgboost/issues/22

**Comment by acalejos** [comment]
@josevalim @santiago-imelio 

I just pushed a patch to EXGBoost v0.5.1 that should fix this. I can make a PR here to update the notebook here
