### ISSUE TITLE
Docs showing white page

### ISSUE THREAD

**Issue by zacksiri** [elixir-nx/scholar#287]
I'm not sure what the issue is but I can't seem to see the documentation when clicking on the modules on the sidebar. I tried in both Chrome and Firefox.

<img width="875" alt="Screenshot 2567-06-27 at 22 12 34" src="https://github.com/elixir-nx/scholar/assets/134488/effa0d64-9be3-421e-b4de-99f1035fc7cc">

**Comment by krstopro** [comment]
Seems to be working fine for me.
<img width="880" alt="Screenshot 2024-06-27 at 17 17 39" src="https://github.com/elixir-nx/scholar/assets/7234787/01e66025-cdc5-488f-94c2-76ec703f9db3">

**Comment by josevalim** [comment]
Did you try a hard refresh? It also works here.

**Comment by billylanchantin** [comment]
@zacksiri Can you paste the URL you're trying to hit? This works for me:

* https://hexdocs.pm/scholar/Scholar.Cluster.Hierarchical.html

But I did just find that an old bookmarked link of mine no longer works, so that might be what's going on.

**Comment by zacksiri** [comment]
Hmm, for some reason it's not working, i guess the problem is on my side.

**Comment by zacksiri** [comment]
I think I know what the problem is. It's on cloudflare side. I SSHed into one of my VPS in another region and ran curl and got a normal output. But it seems the cache server specific to my region is broken. I'm going to have to route my traffic through another node.

**Comment by zacksiri** [comment]
Just to confirm https://www.cloudflarestatus.com/ 
<img width="1009" alt="Screenshot 2567-06-27 at 23 06 33" src="https://github.com/elixir-nx/scholar/assets/134488/84a70c85-aa4d-49c6-8839-28eae85fcd89">


 I happen to be in Bangkok.
