### ISSUE TITLE
`one_hot_encode` errors with tensor of size 1

### ISSUE THREAD

**Issue by aos** [elixir-nx/scholar#290]
Howdy - following up on my [post on elixirforums here](https://elixirforum.com/t/scholar-preprocessing-one-hot-encode-does-not-work/65194), I'm opening the issue here as well per Jose's recommendation.

It seems the issue that the ordinal encoder expects tensors of size >= 2, from this line of code here: https://github.com/elixir-nx/scholar/blob/8712e96189983e56f32050ba91874e115ed70e1d/lib/scholar/preprocessing/ordinal_encoder.ex#L59

**Comment by aos** [comment]
Additionally - it seems like you can't assign an arbitrary number of `num_classes`. I don't think this might be a bug, but it did throw me off coming from PyTorch. Eg. I can't do this:

```elixir
Scholar.Preprocessing.one_hot_encode(Nx.tensor([5, 3]), num_classes: 27)
```
Looks like it's capped at `num_classes <= tensor size`

**Comment by krstopro** [comment]
Hi @aos! Thanks for bringing this up to our attention.
These do seem like bugs, I am having a closer look.
