### ISSUE TITLE
Estimators API

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/scholar#3]
So sklearn builds around a bunch of base estimators (classifiers and regressors). Here I am proposing an API for training and using estimators. I haven't thought through how this may extend to other stateful APIs, but perhaps there will be a natural extension.

First, sklearn essentially builds everything around `fit` and `predict`. So you can basically always depend on:

```python
model = LinearRegression()
model.fit(X, y)

model.predict(X_test)
```

When unpickling trained models you can pretty much depend on this being the API as well:

```python
model = pickle.load(...)
model.predict(...)
```

Obviously we can't take the OO approach which modifies internal state. Instead, what we can do is build estimators from data structures. This is the same approach Axon takes. So essentially you will have a `Scholar` struct:

```elixir
defstruct :estimator, :state, :name, :id
```

Where `:estimator` is the model to run and `:state` is a unique state which is associated with the estimator. For `:linear_regression` this might be a map of coefficients and intercepts. For other models it will be different. Regardless, state will be unique to whatever the `:estimator` is.

Scholar will then expose 2 functions: `predict` and `fit`. Both of which delegate training and prediction logic to an internal compiler based on the estimator. Now, we can construct estimators from constructors:

```elixir
model1 = Scholar.linear_regression(...)
model2 = Scholar.svm(...)
```
And we can introduce some interesting combinators of estimators for pipelines and ensembles.

Finally, I don't believe we should restrict ourselves to only models which can be implemented in pure Nx. For each model we should make a best faith effort to ensure it's efficiently written (e.g. delegate to Nx as much as possible); however, I believe there is a benefit to having models available despite maybe not being pure Nx. Applying the models is important to learning, so just having some parity with sklearn would be huge for beginners. We can worry about optimizing implementations with NIFs or other means later.

Once we finalize on an API I will go through and create a functionality checklist which can guide contributions :)

**Comment by josevalim** [comment]
We have two options:

1. Have a single shared struct, as you described above

2. Make `Scholar` a protocol with a `predict` function. So you do this:

    ```elixir
    model = Scholar.SVM.fit(...)
    Scholar.predict(model, data)
    ```

I am more inclined towards the second because it will give us more flexibility and we don't need to tie everything into a single struct. WDYT?

---

We also need to answer how this will work with `Nx.Container` and pickling. Maybe we should expand `Nx.Container` to have deserialize and serialize functions too. WDYT @seanmor5?

**Comment by seanmor5** [comment]
I like the protocol route. I think we should hold off on adding special serialization for containers right now though and instead if we need scholar specific serialization we can add it. 

With the protocol in mind I will make a list of estimators to reach some parity with sklearn. The API surface will be pretty large

**Comment by cigrainger** [comment]
I agree, I like the protocol idea as well. It should make things easier for other common functions as well. I've been thinking about how `Explorer` will integrate with `Scholar`. Specifically things like sampling and train/test splits, but also ways to rapidly/simply get model information into tidy formats for evaluation and visualisation a la [`broom`](https://broom.tidymodels.org/index.html). A protocol should simplify integration.

@seanmor5 I'm curious about what you have in mind re: models that can't be implemented in pure Nx. Do you mean falling back to plain Elixir? Any models jumping out at you?

**Comment by tiagodavi** [comment]
I like "train/predict" in terms of function names. I think it's clearer than fit/predict.

**Comment by tiagodavi** [comment]
I agree with protocols as well because we can handle other kind of cases like unsupervised learning functions that does not take x/y as arguments.

```
model = Scholar.NearestNeighbors.train(samples)
kneighbors = Scholar.predict(model, data)
```
