### ISSUE TITLE
Specs in Scholar

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/scholar#32]
At this moment, some modules have `@spec` annotation, and others don't.  I'd like to make it consistent throughout the whole module. The best solution is probably getting rid of spec since argument types are tensors and keyword lists only. @josevalim

**Comment by polvalente** [comment]
I would rather add specs where they're missing instead of removing altogether.

Some functions might accept kw, others might accept more than one tensor, and specs would help with disambiguation

**Comment by jonatanklosko** [comment]
+1 for removing specs for `defn`s, I don't think we annotate `defn`s elsewhere. Specs are mostly useful for documentation, and in case of `defn`s the arguments are fairly standardized and the signature should be enough, so to me specs don't offer much value in this case :)

**Comment by josevalim** [comment]
I think we can remove the specs and likely migrate to `NimbleOptions` to specify the options: https://github.com/dashbitco/nimble_options

NimbleOptions will give us more structure and consistency during validation. The only difference is that our `fit` entrypoint will have to be a deftransform:

```elixir
deftransform fit(tensor, opts \\ []) do
  nfit(tensor, NimbleOptions.validate!(@schema, opts))
end
```

My suggestion is to migrate kmeans to NimbleOptions, then we can go around removing the specs. Can you please investigate this @msluszniak?

**Comment by josevalim** [comment]
I likely meant `train` instead of `fit` in the above. :)

**Comment by msluszniak** [comment]
Sure, I will play with the NimbleOptions.
