### ISSUE TITLE
Add imputation of missing values

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/scholar#47]
I think that this feature might be very useful in the future. However, I believe that before implementing that, we would need the official functionality which converts Explorer.DF -> Nx.tensor, Explorer.Series -> Nx.tensor, and reversed transitions.

**Comment by msluszniak** [comment]
What do you think @josevalim?

**Comment by msluszniak** [comment]
@polvalente?

**Comment by polvalente** [comment]
Right. We already have `Nx.is_nan`, `Nx.is_infinity`, `Nx.equal` which could deal with replacing any given value through `Nx.select`. Perhaps this is a nice starting point.

Why would we need functionality to convert between Explorer and Nx to achieve this?

**Comment by msluszniak** [comment]
In almost all cases, when we deal with missing values we load the data from somewhere. Of course, we can implement the imputers without these functions, but the real usage of the imputers demands converting functions.

**Comment by josevalim** [comment]
I will focus on Explorer to Nx conversion in the following weeks, so we can revisit it later. I think featurizers and similar would also be part of this discussion?

**Comment by msluszniak** [comment]
Yes, featurizers are also in the scope of this discussion.
