### ISSUE TITLE
Will there be support for the equivalent of scikit-learn's Scalers?

### ISSUE THREAD

**Issue by danieljaouen** [elixir-nx/scholar#48]
In particular, I am curious about MinMaxScaler and StandardScaler, as seen here: https://scikit-learn.org/stable/modules/preprocessing.html

**Comment by jonatanklosko** [comment]
Hey @danieljaouen, you can have a look at `Scholar.Preprocessing.{standard_scale,min_max_scale}` :)

**Comment by danieljaouen** [comment]
Thank you!
