### ISSUE TITLE
Testing Scholar.Linear.LinearRegression 

### ISSUE THREAD

**Issue by ndrean** [elixir-nx/scholar#62]
While testing LinearRegression fit,  the compiler stops:

```
(UndefinedFunctionError) function Nx.LinAlg.pinv/1 is undefined or private
    (nx 0.4.1) Nx.LinAlg.pinv(#Nx.Tensor<
```

The library Nx.LinAlg has no public `pinv` function

```
defnp lstsq(a, b, a_offset, b_offset, fit_intercept?) do
    pinv = Nx.LinAlg.pinv(a)
...
```

**Comment by polvalente** [comment]
You need to use Nx' GitHub main branch instead of the hex package for now.

**Comment by ndrean** [comment]
What is wrong with the following?
````
Mix.install(
  [
    {:nx, gituhb: "elixir-nx/nx", override: true}, 
    {:kino, "~> 0.8.0"},
    {:exla, "~> 0.4.1"},
    {:scholar, github: "elixir-nx/scholar", override: true}
    ]
)
```

**Comment by polvalente** [comment]
> What is wrong with the following?
> ````
> Mix.install(
>   [
>     {:nx, gituhb: "elixir-nx/nx", override: true}, 
>     {:kino, "~> 0.8.0"},
>     {:exla, "~> 0.4.1"},
>     {:scholar, github: "elixir-nx/scholar", override: true}
>     ]
> )
> ```

Typo on "gituhb" instead of "github" for :nx, and you're also missing the `sparse: "nx"` option there
