### ISSUE TITLE
[Question]: I created a stratified shuffler. What should the API look like?

### ISSUE THREAD

**Issue by appdevland** [elixir-nx/scholar#76]
Hello! Earlier today while fiddling around I made a stratified shuffling algorithm. I want to know what the ideal API for this function would be. Here is my implemenation.

Any suggestions/ideas?

```elixir
defmodule StratifiedShuffle do
  require Explorer.DataFrame

  alias Explorer.DataFrame
  alias Explorer.Series

  def run(original_df, category_column) do
    categories = DataFrame.distinct(original_df, [category_column])
    categories = Series.to_list(categories[category_column])
    
    %{original_df: train_set, stratified_shuffle_df: test_set} = Enum.reduce(categories, %{original_df: original_df, 
    stratified_shuffle_df: original_df |> DataFrame.slice([0, 0])},
     fn category, %{original_df: original_df, stratified_shuffle_df: stratified_shuffle_df} -> 
      testing = DataFrame.filter_with(original_df, fn row ->
        Series.equal(row[category_column], category)
      end
      ) |> DataFrame.sample(0.2, seed: 42)
      
      %{original_df: original_df, stratified_shuffle_df: DataFrame.concat_rows(stratified_shuffle_df, testing)}
    end
    )

    # Remove test samples from training set 
    # also, the code here is badf. Fix when feels like is_tuple(

    train_mapset = DataFrame.to_rows(train_set) |> MapSet.new()
    test_mapset = DataFrame.to_rows(test_set) |> MapSet.new()

    train_mapset = MapSet.difference(train_mapset, test_mapset)

    train_set = train_mapset |> MapSet.to_list() |> Explorer.DataFrame.new()
    
    {train_set, test_set}
  end
end
```

The code can be cleaned up. But what I want to know is where would I add this function to Scholar? I looked through Scholar's code and no modules seemed to be a good place to store this functionality.

**Comment by josevalim** [comment]
At the moment I don't think it belongs here because we are a library around Nx rather than dataframes. I guess we will see in the future how it will evolve, but no place for now :) Thanks for sharing anyway

**Comment by appdevland** [comment]
IIt seems like using and benefitting from dataframes would be an integral part of this project.

The impression I got when looking through the README was that Scholar is scikit-learn for Elixir. Hence, my issue submission.

Would you consider adding this feature to Scholar if it was implemented with Nx? (I haven't used Nx directly but am willing to try and implement stratified shuffling with it)

**Comment by josevalim** [comment]
Yes, if you implement it with Nx, then it will be welcome. :)

It is like scikit-learn for Elixir, but build around a tensor compiler rather than dataframes. I will amend the README.
